version: '3'
services:

  db:
    image: mariadb:5.5.57
    container_name: database
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: qul_d7_db
        MYSQL_USER: drupal
        MYSQL_PASSWORD: drupal

  memcached:
    hostname: memcached
    image: memcached:latest
    container_name: memcached
    environment:
    # Memcached memory limit in megabytes
    - MEMCACHED_MEMORY_LIMIT=1024
    ports:
      - "11211:11211"
    # command: memcached -m 1024m

  web:
    # image: drupal:7.56
    image: qul_web
    build: ./config/web
    container_name: web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html:cached
      - ./site-backups:/var/www/sites-backups
      - /Applications/drush-7.x:/drush
    links:
      - db
      - memcached

volumes:
  data:
  www:
  site-backups:
